# Build settings
gems:
  - rouge
  - jemoji
  - jekyll-paginate

# Site settings
title: Pitzcarraldo's Devlog
description: Monologue About The Development

email: mrnoname@naver.com
logo: "/assets/icons/icon_048.png"
cover_logo: "/assets/images/author.jpg"
cover: "/assets/images/about-bg.jpg"

name: "Minkyu Cho"
author: "Minkyu Cho"
author_image: "/assets/images/author.jpg"

paginate: 5

url: //Pitzcarraldo.github.io
twitter_handle: "@pitzcarraldo"

disqus: pitzcarraldo
google_analytics: UA-53163981-1

highlighter: rouge
permalink: pretty
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript","footnotes"]
kramdown:
  input: GFM
  enable_coderay: false

social:
  - icon: twitter
    url: https://twitter.com/pitzcarraldo
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    url: https://facebook.com/pitzcarraldo
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: github
    url: https://github.com/pitzcarraldo
    desc: Fork me on github

  - icon: linkedin
    url:  https://kr.linkedin.com/in/pitzcarraldo
    desc: Connect with me linkedin
